<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.Winforms" Version="150.1652.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseManagementSystem.Business\WarehouseManagementSystem.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="ReportDatasets\ItemsCloseToExpirationDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ItemsCloseToExpirationDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="ReportDatasets\ItemsInWarehousePeriodDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ItemsInWarehousePeriodDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="ReportDatasets\WarehousesItemsDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WarehousesItemsDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="ReportDatasets\WarehouseStatusDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WarehouseStatusDataSet.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="ReportDatasets\ItemsCloseToExpirationDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ItemsCloseToExpirationDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="ReportDatasets\ItemsInWarehousePeriodDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ItemsInWarehousePeriodDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="ReportDatasets\WarehousesItemsDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>WarehousesItemsDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="ReportDatasets\WarehouseStatusDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>WarehouseStatusDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\ItemsCloseToExpirationReport.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\ItemsInWarehousePeriodReport.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\WarehousesItemsReport.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\WarehouseStatusReport.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\" />
  </ItemGroup>

</Project>